services:
  - type: web
    name: metro-cuadrado-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 30 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
